export {default as Header} from './Header'
export {default as Blog} from './Blog'
export {default as FinalResult} from './FinalResult'
export {default as TopPlayers} from './TopPlayers'
export {default as TopVideo} from './TopVideo'
export {default as OurTeam} from './OurTeam'
export {default as Subscribe} from './Subscribe'
export {default as Footer} from './Footer'